"""Workspace management — lab folder layout, metadata persistence, scan discovery."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field, fields
from datetime import datetime, timezone
from pathlib import Path

from . import nmap as _nmap

METADATA_FILENAME = ".reconlab.json"
WORKSPACE_FOLDERS: tuple[str, ...] = (
    "scans",
    "screenshots",
    "loot",
    "notes",
    "exploits",
    "creds",
    "web",
)
SCAN_EXTENSIONS: tuple[str, ...] = (".xml", ".nmap", ".gnmap")
WEB_EXTENSIONS: tuple[str, ...] = (".txt", ".json")


@dataclass
class WorkspaceMetadata:
    name: str
    target_ip: str | None = None
    target_host: str | None = None
    domain: str | None = None
    platform: str = "lab"
    status: str = "in-progress"
    created_at: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> "WorkspaceMetadata":
        known = {f.name for f in fields(cls)}
        return cls(**{k: v for k, v in data.items() if k in known})

    def to_dict(self) -> dict:
        return asdict(self)


def metadata_path(workspace: Path) -> Path:
    return workspace / METADATA_FILENAME


def read_metadata(workspace: Path) -> WorkspaceMetadata:
    path = metadata_path(workspace)
    if not path.is_file():
        raise FileNotFoundError(
            f"No workspace metadata at {path}. "
            "Run `reconlab workspace init <name>` first."
        )
    data = json.loads(path.read_text(encoding="utf-8"))
    return WorkspaceMetadata.from_dict(data)


def write_metadata(workspace: Path, metadata: WorkspaceMetadata) -> None:
    metadata_path(workspace).write_text(
        json.dumps(metadata.to_dict(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def report_scaffold(metadata: WorkspaceMetadata) -> str:
    ip = metadata.target_ip or "[TARGET_IP]"
    host = metadata.target_host or "[TARGET_HOST]"
    domain = metadata.domain or "[DOMAIN]"
    platform = metadata.platform
    created = metadata.created_at or _utc_now_iso()

    lines = [
        "---",
        f"title: {metadata.name} — Engagement Report",
        f"target_ip: {ip}",
        f"target_host: {host}",
        f"domain: {domain}",
        f"platform: {platform}",
        "status: in-progress",
        f"created: {created}",
        "tags:",
        "  - report",
        f"  - {platform}",
        "---",
        "",
        f"# {metadata.name}",
        "",
        "## Metadata",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| Target IP | `{ip}` |",
        f"| Target host | `{host}` |",
        f"| Domain | `{domain}` |",
        f"| Platform | {platform} |",
        "| Status | in-progress |",
        f"| Started | {created} |",
        "",
        "## Scope",
        "",
        "- Authorized lab target only — do not exceed engagement scope.",
        "- Source IP: `[LHOST]`",
        "- Allowed: enumeration, exploitation within scope, lab-safe credential validation.",
        "- Disallowed: out-of-scope targets, destructive actions, real-world exfiltration.",
        "",
        "## Executive Summary",
        "",
        "_Fill after engagement completes — 2-3 sentence summary of overall impact._",
        "",
        "## Methodology",
        "",
        "See [[notes/methodology/index]] (generated by `reconlab workspace suggest`) "
        "for the prioritized service-by-service methodology. Update findings inline "
        "as work progresses.",
        "",
        "## Findings",
        "",
        "### Finding 1 — _Title_",
        "",
        "- **Severity:** _Critical | High | Medium | Low | Info_",
        f"- **Affected:** `{ip}` — `[SERVICE]:[PORT]`",
        "- **Description:** _What is the issue?_",
        "- **Evidence:** see `screenshots/finding-1-*.png`",
        "- **Impact:** _Business or technical impact._",
        "- **Remediation:** _Specific, actionable fix — not generic advice._",
        "",
        "## Evidence Index",
        "",
        "| Folder | Contents |",
        "|--------|----------|",
        "| `scans/` | Raw nmap output (xml / nmap / gnmap) |",
        "| `screenshots/` | Annotated screenshots, one set per finding |",
        "| `loot/` | Recovered files (sanitized before report) |",
        "| `notes/` | Working notes and generated methodology |",
        "| `exploits/` | Adapted exploit code with attribution |",
        "| `creds/` | Recovered credentials — keep local, never commit |",
        "",
        "## Lessons Learned",
        "",
        "- _What surprised you?_",
        "- _What would you do differently next time?_",
        "",
        "## Appendix",
        "",
        "### Tools used",
        "",
        "- _nmap, feroxbuster, nxc, evil-winrm, impacket, ..._",
        "",
        "### References",
        "",
        "- _Links to relevant manual sections, CVEs, vendor advisories._",
        "",
    ]
    return "\n".join(lines)


def init_workspace(
    workspace: Path,
    *,
    name: str,
    target_ip: str | None = None,
    target_host: str | None = None,
    domain: str | None = None,
    platform: str = "lab",
    force: bool = False,
) -> WorkspaceMetadata:
    """Create the workspace folder tree, metadata file, and report scaffold."""
    if workspace.exists() and not force:
        if metadata_path(workspace).exists():
            raise FileExistsError(
                f"Workspace already initialized at {workspace}. Pass --force to overwrite."
            )

    workspace.mkdir(parents=True, exist_ok=True)
    for folder in WORKSPACE_FOLDERS:
        (workspace / folder).mkdir(parents=True, exist_ok=True)

    metadata = WorkspaceMetadata(
        name=name,
        target_ip=target_ip,
        target_host=target_host,
        domain=domain,
        platform=platform,
        created_at=_utc_now_iso(),
    )
    write_metadata(workspace, metadata)

    report_path = workspace / "report.md"
    if force or not report_path.exists():
        report_path.write_text(report_scaffold(metadata), encoding="utf-8")

    return metadata


def find_latest_scan(scans_dir: Path) -> Path | None:
    """Return the most-recently-modified scan file by mtime, restricted to known formats."""
    if not scans_dir.is_dir():
        return None
    candidates = [
        path
        for path in scans_dir.iterdir()
        if path.is_file() and path.suffix.lower() in SCAN_EXTENSIONS
    ]
    if not candidates:
        return None
    return max(candidates, key=lambda p: p.stat().st_mtime)


def find_all_scans(scans_dir: Path) -> list[Path]:
    """Return every scan file (.xml/.nmap/.gnmap) in scans_dir, ordered oldest-first by mtime."""
    if not scans_dir.is_dir():
        return []
    candidates = [
        path
        for path in scans_dir.iterdir()
        if path.is_file() and path.suffix.lower() in SCAN_EXTENSIONS
    ]
    return sorted(candidates, key=lambda p: p.stat().st_mtime)


def find_all_web_files(web_dir: Path) -> list[Path]:
    """Return every web-output file (.txt/.json) in web_dir, ordered oldest-first by mtime."""
    if not web_dir.is_dir():
        return []
    candidates = [
        path
        for path in web_dir.iterdir()
        if path.is_file() and path.suffix.lower() in WEB_EXTENSIONS
    ]
    return sorted(candidates, key=lambda p: p.stat().st_mtime)


@dataclass
class AggregatedHostname:
    """A deduplicated hostname with every source that mentioned it."""

    hostname: str
    sources: list[str] = field(default_factory=list)


def collect_hostname_candidates(
    workspace: Path,
    *,
    target_ip: str | None = None,
) -> tuple[str | None, list[AggregatedHostname]]:
    """Aggregate hostname candidates for a workspace.

    Pulls from `.reconlab.json` (target_host, target_host + domain as FQDN)
    and every XML scan in `scans/`. Filters scan candidates to those whose
    IP matches the workspace target IP (from metadata or the explicit
    `target_ip` override). Scan candidates with no IP attached are kept.

    Returns (resolved_target_ip, aggregated_hostnames). Deduplication is
    case-insensitive; the first-seen casing wins; sources accumulate in
    order of discovery.
    """
    metadata = read_metadata(workspace)
    resolved_ip = target_ip if target_ip is not None else metadata.target_ip

    raw: list[_nmap.HostnameCandidate] = []

    if metadata.target_host:
        raw.append(
            _nmap.HostnameCandidate(
                hostname=metadata.target_host,
                source="metadata target_host",
                ip=resolved_ip,
            )
        )
        if metadata.domain and "." not in metadata.target_host:
            fqdn = f"{metadata.target_host}.{metadata.domain}"
            raw.append(
                _nmap.HostnameCandidate(
                    hostname=fqdn,
                    source="metadata target_host + domain",
                    ip=resolved_ip,
                )
            )

    scans_dir = workspace / "scans"
    for scan_path in find_all_scans(scans_dir):
        if scan_path.suffix.lower() != ".xml":
            continue
        for candidate in _nmap.extract_hostname_candidates(scan_path):
            if (
                resolved_ip is not None
                and candidate.ip is not None
                and candidate.ip != resolved_ip
            ):
                continue
            raw.append(candidate)

    aggregated: dict[str, AggregatedHostname] = {}
    for cand in raw:
        key = cand.hostname.lower()
        if key not in aggregated:
            aggregated[key] = AggregatedHostname(hostname=cand.hostname, sources=[])
        if cand.source not in aggregated[key].sources:
            aggregated[key].sources.append(cand.source)

    return resolved_ip, list(aggregated.values())
